//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKHeX.EncounterSlotDumper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PKHeX.EncounterSlotDumper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_a {
            get {
                object obj = ResourceManager.GetObject("encounter_a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_b {
            get {
                object obj = ResourceManager.GetObject("encounter_b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_b2 {
            get {
                object obj = ResourceManager.GetObject("encounter_b2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_blue {
            get {
                object obj = ResourceManager.GetObject("encounter_blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_blue_jp {
            get {
                object obj = ResourceManager.GetObject("encounter_blue_jp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_blue_jp_f {
            get {
                object obj = ResourceManager.GetObject("encounter_blue_jp_f", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_crystal {
            get {
                object obj = ResourceManager.GetObject("encounter_crystal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_crystal_h {
            get {
                object obj = ResourceManager.GetObject("encounter_crystal_h", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_d {
            get {
                object obj = ResourceManager.GetObject("encounter_d", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_e {
            get {
                object obj = ResourceManager.GetObject("encounter_e", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_fr {
            get {
                object obj = ResourceManager.GetObject("encounter_fr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_ge {
            get {
                object obj = ResourceManager.GetObject("encounter_ge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_gold {
            get {
                object obj = ResourceManager.GetObject("encounter_gold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_gold_h {
            get {
                object obj = ResourceManager.GetObject("encounter_gold_h", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_gp {
            get {
                object obj = ResourceManager.GetObject("encounter_gp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_gsc_f {
            get {
                object obj = ResourceManager.GetObject("encounter_gsc_f", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_hb_hg {
            get {
                object obj = ResourceManager.GetObject("encounter_hb_hg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_hb_ss {
            get {
                object obj = ResourceManager.GetObject("encounter_hb_ss", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_hg {
            get {
                object obj = ResourceManager.GetObject("encounter_hg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_lg {
            get {
                object obj = ResourceManager.GetObject("encounter_lg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_mn {
            get {
                object obj = ResourceManager.GetObject("encounter_mn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_mn_sos {
            get {
                object obj = ResourceManager.GetObject("encounter_mn_sos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_o {
            get {
                object obj = ResourceManager.GetObject("encounter_o", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_p {
            get {
                object obj = ResourceManager.GetObject("encounter_p", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_pt {
            get {
                object obj = ResourceManager.GetObject("encounter_pt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_r {
            get {
                object obj = ResourceManager.GetObject("encounter_r", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_rb_f {
            get {
                object obj = ResourceManager.GetObject("encounter_rb_f", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_red {
            get {
                object obj = ResourceManager.GetObject("encounter_red", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_s {
            get {
                object obj = ResourceManager.GetObject("encounter_s", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_silver {
            get {
                object obj = ResourceManager.GetObject("encounter_silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_silver_h {
            get {
                object obj = ResourceManager.GetObject("encounter_silver_h", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_sn {
            get {
                object obj = ResourceManager.GetObject("encounter_sn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_sn_sos {
            get {
                object obj = ResourceManager.GetObject("encounter_sn_sos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_ss {
            get {
                object obj = ResourceManager.GetObject("encounter_ss", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_um {
            get {
                object obj = ResourceManager.GetObject("encounter_um", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_um_sos {
            get {
                object obj = ResourceManager.GetObject("encounter_um_sos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_us {
            get {
                object obj = ResourceManager.GetObject("encounter_us", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_us_sos {
            get {
                object obj = ResourceManager.GetObject("encounter_us_sos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_w {
            get {
                object obj = ResourceManager.GetObject("encounter_w", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_w2 {
            get {
                object obj = ResourceManager.GetObject("encounter_w2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_x {
            get {
                object obj = ResourceManager.GetObject("encounter_x", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_y {
            get {
                object obj = ResourceManager.GetObject("encounter_y", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_yellow {
            get {
                object obj = ResourceManager.GetObject("encounter_yellow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_yellow_f {
            get {
                object obj = ResourceManager.GetObject("encounter_yellow_f", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species	Level	Move1	Move2	Move3	Move4	Lang	Trainer	ID	OT	IV_HP	IV_ATK	IV_DEF	IV_SPE	IV_SPA	IV_SPD	Comment
        ///151	05	001				0	1	22796	VC	15	15	15	15	15	15	GF/ゲーフリ
        ///001	05	033	045			0	2	2000	STAD*							STADIUM
        ///004	05	010	045			0	2	2000	STAD*							STADIUM
        ///007	05	033	039			0	2	2000	STAD*							STADIUM
        ///054	15	010	133			0	2	2000	STAD*							STADIUM
        ///106	20	024	096			0	2	2000	STAD*							STADIUM
        ///107	20	004	097			0	2	2000	STAD*							STADIUM
        ///133	25	033	039			0	2	2000	STAD*							STADIUM
        ///138	20	055	110			0	2	2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string event1 {
            get {
                return ResourceManager.GetString("event1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species	Level	Move1	Move2	Move3	Move4	Met	Current	IsShiny	IsEgg	Lang	Trainer	OT	ID	Comment
        ///83	5	226	14	97	163	127				1	1	スタジアム	2000	
        ///207	5	89	68	17		127				1	1	スタジアム	2000	
        ///83	5	226	14	97	163	127				2	2	Stadium	2000	
        ///207	5	89	68	17		127				2	2	Stadium	2000	
        ///83	5	226	14	97	163	127				3	3	Stad*	2001	
        ///207	5	89	68	17		127				3	3	Stad*	2001	
        ///151	5	1				127		True		0	4	PCNY*		
        ///251	5	73	93	215	105	127				0	4	PCNY*		
        ///243	5	43	84	46	98	127	40	True		0	4	PCNY*		
        ///244	5	43	52	46	83	127	40	True		0	4	PCNY*		
        ///245	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string event2 {
            get {
                return ResourceManager.GetString("event2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] personal_e {
            get {
                object obj = ResourceManager.GetObject("personal_e", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] personal_hgss {
            get {
                object obj = ResourceManager.GetObject("personal_hgss", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] safari_a230 {
            get {
                object obj = ResourceManager.GetObject("safari_a230", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None)
        ///New Bark Town
        ///Route 29
        ///Cherrygrove City
        ///Route 30
        ///Route 31
        ///Violet City
        ///Sprout Tower
        ///Route 32
        ///Ruins of Alph
        ///Union Cave
        ///Route 33
        ///Azalea Town
        ///Slowpoke Well
        ///Ilex Forest
        ///Route 34
        ///Goldenrod City
        ///Goldenrod Radio Tower
        ///Route 35
        ///National Park
        ///Route 36
        ///Route 37
        ///Ecruteak City
        ///Tin Tower
        ///Burned Tower
        ///Route 38
        ///Route 39
        ///Olivine City
        ///Lighthouse
        ///Battle Tower
        ///Route 40
        ///Whirl Islands
        ///Route 41
        ///Cianwood City
        ///Route 42
        ///Mt. Mortar
        ///Mahogany Town
        ///Route 43
        ///Lake of Rage
        ///Route 44
        ///Ice Path
        ///Blackthorn City
        ///Dragon&apos;s Den
        ///Route 45
        ///Dark [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_gsc_00000_en {
            get {
                return ResourceManager.GetString("text_gsc_00000_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] trees {
            get {
                object obj = ResourceManager.GetObject("trees", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] trees_h_c {
            get {
                object obj = ResourceManager.GetObject("trees_h_c", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] walker_enc {
            get {
                object obj = ResourceManager.GetObject("walker_enc", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
